DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films_genres CASCADE;
DROP TABLE IF EXISTS users_friends CASCADE;
DROP TABLE IF EXISTS users_films_likes CASCADE;

CREATE TABLE IF NOT EXISTS films
(
    film_id      INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rating_id    INT     NOT NULL,
    film_name    VARCHAR NOT NULL,
    description  VARCHAR NOT NULL,
    release_date DATE    NOT NULL,
    duration     INT     NOT NULL
);
CREATE TABLE IF NOT EXISTS genres
(
    genre_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS ratings
(
    rating_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS users
(
    user_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR NOT NULL,
    login     VARCHAR NOT NULL,
    user_name VARCHAR NOT NULL,
    birthday  date
);
CREATE TABLE IF NOT EXISTS films_genres
(
    film_id  integer,
    genre_id integer
);
CREATE TABLE IF NOT EXISTS users_friends
(
    user_id   integer,
    friend_id integer
);
CREATE TABLE IF NOT EXISTS users_films_likes
(
    user_id integer,
    film_id integer,
    PRIMARY KEY (user_id, film_id)
);
ALTER TABLE
    films
    ADD
        FOREIGN KEY (rating_id) REFERENCES ratings (rating_id);
ALTER TABLE
    films_genres
    ADD
        FOREIGN KEY (film_id) REFERENCES films (film_id);
ALTER TABLE
    films_genres
    ADD
        FOREIGN KEY (genre_id) REFERENCES genres (genre_id);
ALTER TABLE
    users_friends
    ADD
        FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE
    users_friends
    ADD
        FOREIGN KEY (friend_id) REFERENCES users (user_id);
ALTER TABLE
    users_films_likes
    ADD
        FOREIGN KEY (user_id) REFERENCES users (user_id);
ALTER TABLE
    users_films_likes
    ADD
        FOREIGN KEY (film_id) REFERENCES films (film_id);

